#!/bin/bash
repo_name=$1
user=pjayaraj1989
test -z $repo_name && echo "Repo name reqd. " 1>&2 && exit 1

curl -u "@user" https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}";

#make this executable and run as
#git-create <repo name>
#then
#git init
#git remote add origin "https/github.com/$user/$repo_name.git"

